"""PDF generation for RFQs, quotations, orders and proofs of payment.

Built on fpdf2 (pure Python, no system libraries). If the dependency is missing
the builders return ``None`` so callers degrade to sending the email without an
attachment rather than failing the request.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from typing import Sequence

from app.core.shared.config import get_settings
from app.services.shared.notifications.email_templates import EmailAttachment

logger = logging.getLogger(__name__)

TEAL = (0, 97, 97)
GREEN = (0, 170, 109)
HEADING = (51, 66, 87)
BODY = (95, 107, 116)
MUTED = (139, 149, 157)
LINE = (223, 231, 229)
SOFT = (246, 250, 249)

_UNICODE_FALLBACKS = {
    "\u2014": "-",
    "\u2013": "-",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2022": "-",
    "\u00b7": "-",
    "\u2026": "...",
    "\u00a0": " ",
    "\u20ac": "EUR",
    "\u2192": "->",
}


def _latin(value: str | None) -> str:
    """Core PDF fonts are Latin-1 only; normalise anything outside that range."""

    text = str(value or "")
    for source, target in _UNICODE_FALLBACKS.items():
        text = text.replace(source, target)
    return text.encode("latin-1", "replace").decode("latin-1")


@dataclass
class DocumentParty:
    label: str
    lines: Sequence[str]


@dataclass
class DocumentSection:
    title: str
    rows: Sequence[tuple[str, str | None]]


@dataclass
class DocumentLineItem:
    description: str
    detail: str | None = None
    amount: str = ""


@dataclass
class DocumentSpec:
    title: str
    reference: str
    issued_on: str | None = None
    status: str | None = None
    intro: str | None = None
    parties: Sequence[DocumentParty] = ()
    sections: Sequence[DocumentSection] = ()
    line_items: Sequence[DocumentLineItem] = ()
    totals: Sequence[tuple[str, str]] = ()
    notes: Sequence[tuple[str, str]] = field(default_factory=list)
    footer_note: str | None = None


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%d %b %Y")


def format_doc_date(value: datetime | date | None) -> str:
    if value is None:
        return "-"
    return value.strftime("%d %b %Y")


def _slug(value: str) -> str:
    keep = [c if c.isalnum() or c in "-_" else "-" for c in value.strip()]
    return "".join(keep).strip("-") or "document"


def render_document_pdf(spec: DocumentSpec) -> bytes | None:
    try:
        from fpdf import FPDF
        from fpdf.enums import XPos, YPos
    except ImportError:  # pragma: no cover - depends on deployment image
        logger.warning("fpdf2 is not installed; skipping PDF generation")
        return None

    settings = get_settings()
    site_url = settings.frontend_base_url.rstrip("/")
    footer_note = spec.footer_note or (
        "Generated by MIU Export Hub. All trade is facilitated and escrowed by "
        "Made in Uganda."
    )

    class _Document(FPDF):
        def footer(self) -> None:
            self.set_y(-18)
            self.set_draw_color(*LINE)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(2)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*MUTED)
            self.multi_cell(
                self.w - self.l_margin - self.r_margin,
                4,
                _latin(footer_note),
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
            )

    pdf = _Document(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=26)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()
    width = pdf.w - pdf.l_margin - pdf.r_margin

    def line_break(height: float = 4.0) -> None:
        pdf.ln(height)

    def label_value_row(label: str, value: str, *, label_w: float = 42.0) -> None:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(label_w, 6, _latin(label.upper()))
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*HEADING)
        pdf.multi_cell(
            width - label_w, 6, _latin(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )

    def section_title(text: str) -> None:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*TEAL)
        pdf.cell(
            width, 7, _latin(text.upper()), new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        pdf.set_draw_color(*LINE)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + width, pdf.get_y())
        line_break(2)

    # Header band
    pdf.set_fill_color(*TEAL)
    pdf.rect(0, 0, pdf.w, 26, style="F")
    pdf.set_xy(pdf.l_margin, 8)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(width / 2, 8, "Made in Uganda")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_xy(pdf.l_margin + width / 2, 9)
    pdf.cell(width / 2, 7, _latin(site_url), align="R")
    pdf.set_xy(pdf.l_margin, 15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(210, 232, 230)
    pdf.cell(width, 6, "Export Hub", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_y(34)
    pdf.set_font("Helvetica", "B", 19)
    pdf.set_text_color(*HEADING)
    pdf.cell(width, 10, _latin(spec.title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*BODY)
    meta = [f"Reference: {spec.reference}", f"Issued: {spec.issued_on or _today()}"]
    if spec.status:
        meta.append(f"Status: {spec.status}")
    pdf.cell(
        width, 6, _latin("   |   ".join(meta)), new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    line_break(4)

    if spec.intro:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*BODY)
        pdf.multi_cell(
            width, 5.5, _latin(spec.intro), new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        line_break(4)

    if spec.parties:
        column = width / max(len(spec.parties), 1)
        top = pdf.get_y()
        bottom = top
        for index, party in enumerate(spec.parties):
            pdf.set_xy(pdf.l_margin + index * column, top)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*MUTED)
            pdf.cell(
                column - 4,
                6,
                _latin(party.label.upper()),
                new_x=XPos.LEFT,
                new_y=YPos.NEXT,
            )
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*HEADING)
            for text in party.lines:
                if not text:
                    continue
                pdf.set_x(pdf.l_margin + index * column)
                pdf.multi_cell(
                    column - 4, 5.2, _latin(text), new_x=XPos.LEFT, new_y=YPos.NEXT
                )
            bottom = max(bottom, pdf.get_y())
        pdf.set_y(bottom)
        line_break(5)

    for section in spec.sections:
        rows = [(label, value) for label, value in section.rows if str(value or "").strip()]
        if not rows:
            continue
        section_title(section.title)
        for label, value in rows:
            label_value_row(label, str(value))
        line_break(4)

    if spec.line_items:
        section_title("Items")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(width * 0.68, 7, "DESCRIPTION")
        pdf.cell(
            width * 0.32, 7, "AMOUNT", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        for item in spec.line_items:
            top = pdf.get_y()
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*HEADING)
            pdf.multi_cell(
                width * 0.68,
                5.5,
                _latin(item.description),
                new_x=XPos.LEFT,
                new_y=YPos.NEXT,
            )
            if item.detail:
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*BODY)
                pdf.multi_cell(
                    width * 0.68,
                    5,
                    _latin(item.detail),
                    new_x=XPos.LEFT,
                    new_y=YPos.NEXT,
                )
            row_bottom = pdf.get_y()
            pdf.set_xy(pdf.l_margin + width * 0.68, top)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*HEADING)
            pdf.cell(width * 0.32, 5.5, _latin(item.amount), align="R")
            pdf.set_y(row_bottom + 1)
            pdf.set_draw_color(*LINE)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + width, pdf.get_y())
            line_break(3)

    if spec.totals:
        line_break(1)
        for index, (label, value) in enumerate(spec.totals):
            emphasis = index == len(spec.totals) - 1
            pdf.set_font("Helvetica", "B" if emphasis else "", 12 if emphasis else 10)
            pdf.set_text_color(*(HEADING if emphasis else BODY))
            pdf.cell(width * 0.68, 7, _latin(label), align="R")
            pdf.set_text_color(*(GREEN if emphasis else HEADING))
            pdf.cell(
                width * 0.32,
                7,
                _latin(value),
                align="R",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
            )
        line_break(5)

    for title, text in spec.notes:
        if not str(text or "").strip():
            continue
        section_title(title)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*BODY)
        pdf.multi_cell(width, 5.5, _latin(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        line_break(4)

    output = pdf.output()
    return bytes(output)


def build_document_attachment(spec: DocumentSpec, *, filename: str) -> EmailAttachment | None:
    try:
        content = render_document_pdf(spec)
    except Exception:
        logger.exception("Failed to render PDF document %s", spec.reference)
        return None
    if not content:
        return None
    return EmailAttachment(filename=filename, content=content, mime_type="application/pdf")


def rfq_document(
    *,
    reference: str,
    issued_on: str | None,
    buyer_lines: Sequence[str],
    supplier_lines: Sequence[str],
    product_name: str,
    quantity_label: str,
    destination: str | None,
    target_price: str | None,
    incoterm: str | None,
    needed_by: str | None,
    requirements: str | None,
) -> EmailAttachment | None:
    spec = DocumentSpec(
        title="Request for Quotation",
        reference=reference,
        issued_on=issued_on,
        intro=(
            "This request for quotation was raised on MIU Export Hub. Please respond "
            "through the platform so the MIU trade desk can review and route your quote."
        ),
        parties=[
            DocumentParty("Buyer", buyer_lines),
            DocumentParty("Supplier", supplier_lines),
        ],
        sections=[
            DocumentSection(
                "Request details",
                [
                    ("Product", product_name),
                    ("Quantity", quantity_label),
                    ("Destination", destination),
                    ("Target price", target_price),
                    ("Incoterm", incoterm),
                    ("Needed by", needed_by),
                ],
            )
        ],
        notes=[("Requirements", requirements or "")],
    )
    return build_document_attachment(spec, filename=f"RFQ-{_slug(reference)}.pdf")


def quotation_document(
    *,
    reference: str,
    quote_reference: str,
    issued_on: str | None,
    valid_until: str | None,
    buyer_lines: Sequence[str],
    supplier_lines: Sequence[str],
    product_name: str,
    quantity_label: str,
    unit_price: str,
    total_price: str,
    incoterm: str | None,
    lead_time: str | None,
    shipment_terms: str | None,
    notes: str | None,
) -> EmailAttachment | None:
    spec = DocumentSpec(
        title="Quotation",
        reference=quote_reference,
        issued_on=issued_on,
        status="Reviewed by MIU trade desk",
        intro=(
            f"Quotation issued in response to RFQ {reference} on MIU Export Hub."
        ),
        parties=[
            DocumentParty("Quoted to", buyer_lines),
            DocumentParty("Quoted by", supplier_lines),
        ],
        sections=[
            DocumentSection(
                "Commercial terms",
                [
                    ("RFQ reference", reference),
                    ("Incoterm", incoterm),
                    ("Lead time", lead_time),
                    ("Shipment terms", shipment_terms),
                    ("Valid until", valid_until),
                ],
            )
        ],
        line_items=[
            DocumentLineItem(
                description=product_name,
                detail=f"{quantity_label} at {unit_price}",
                amount=total_price,
            )
        ],
        totals=[("Total", total_price)],
        notes=[("Supplier notes", notes or "")],
        footer_note=(
            "Acceptance of this quotation on MIU Export Hub creates an escrowed order. "
            "Prices are exclusive of duties and taxes unless stated otherwise."
        ),
    )
    return build_document_attachment(
        spec, filename=f"Quotation-{_slug(quote_reference)}.pdf"
    )


def order_document(
    *,
    reference: str,
    issued_on: str | None,
    status: str | None,
    buyer_lines: Sequence[str],
    supplier_lines: Sequence[str],
    product_name: str,
    quantity_label: str,
    unit_price: str | None,
    total_value: str,
    upfront: str | None,
    balance: str | None,
    incoterm: str | None,
    lead_time: str | None,
    rfq_reference: str | None,
) -> EmailAttachment | None:
    totals: list[tuple[str, str]] = []
    if upfront:
        totals.append(("Upfront due", upfront))
    if balance:
        totals.append(("Balance on milestones", balance))
    totals.append(("Order total", total_value))
    spec = DocumentSpec(
        title="Order Confirmation",
        reference=reference,
        issued_on=issued_on,
        status=status,
        intro=(
            "This order is facilitated by Made in Uganda. Buyer funds are held in "
            "escrow and released to the supplier against agreed milestones."
        ),
        parties=[
            DocumentParty("Buyer", buyer_lines),
            DocumentParty("Supplier", supplier_lines),
        ],
        sections=[
            DocumentSection(
                "Order details",
                [
                    ("RFQ reference", rfq_reference),
                    ("Incoterm", incoterm),
                    ("Lead time", lead_time),
                ],
            )
        ],
        line_items=[
            DocumentLineItem(
                description=product_name,
                detail=(
                    f"{quantity_label} at {unit_price}" if unit_price else quantity_label
                ),
                amount=total_value,
            )
        ],
        totals=totals,
    )
    return build_document_attachment(spec, filename=f"Order-{_slug(reference)}.pdf")


def payment_receipt_document(
    *,
    reference: str,
    order_reference: str,
    issued_on: str | None,
    payment_type_label: str,
    amount: str,
    method: str | None,
    payment_reference: str | None,
    paid_at: str | None,
    buyer_lines: Sequence[str],
    supplier_lines: Sequence[str],
    product_name: str,
    order_total: str | None,
    note: str | None,
) -> EmailAttachment | None:
    spec = DocumentSpec(
        title="Proof of Payment",
        reference=reference,
        issued_on=issued_on,
        status=payment_type_label,
        intro=(
            f"Made in Uganda confirms the payment below against order {order_reference}."
        ),
        parties=[
            DocumentParty("Paid by", buyer_lines),
            DocumentParty("For the benefit of", supplier_lines),
        ],
        sections=[
            DocumentSection(
                "Payment details",
                [
                    ("Order", order_reference),
                    ("Product", product_name),
                    ("Payment type", payment_type_label),
                    ("Method", method),
                    ("Reference", payment_reference),
                    ("Date received", paid_at),
                    ("Order total", order_total),
                ],
            )
        ],
        totals=[("Amount received", amount)],
        notes=[("Note", note or "")],
        footer_note=(
            "This receipt is issued by Made in Uganda as escrow facilitator and is not "
            "a tax invoice."
        ),
    )
    return build_document_attachment(spec, filename=f"POP-{_slug(reference)}.pdf")
